# Generated by Django 5.1.5 on 2025-02-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_time', '-created_time']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('ui/ux', 'ui/ux'), ('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('Graphic', 'Graphic'), ('Product', 'Product'), ('Project', 'Project')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
